from stock import *
saisir_stock(3)
afficher_stock()
supprimer_produit('pc')
afficher_stock()
vendre_produit('mo',10)
afficher_stock()
vendre_produit('mo',70)
afficher_stock()
acheter_produit('mo',40)
afficher_stock()
acheter_produit('mo',20)
afficher_stock()
modifier_produit('rfg','rg',2000,30)
afficher_stock()

